name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write  # Required for OIDC
  contents: write # Required to create GH releases
  pull-requests: write # Required to interact with PRs

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24 # NPM v11.5.1 or later is required for OIDC, which ships with node v24
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}